version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"  # Expose Flask app on port 5000 inside the container, mapped to port 5001 on the host
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=./
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: flask_db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
